version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - nba-network


  backend:
    build:
      context: ./nba-zone
    secrets:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - nba-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  
    secrets:
      - service_id
      - template_id
      - public_key
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
      - TEMPLATE_ID_FILE=/run/secrets/template_id
      - SERVICE_ID_FILE=/run/secrets/service_id
      - PUBLIC_KEY_FILE=/run/secrets/public_key
    ports:
      - "3000:3000"
    networks:
      - nba-network

networks:
  nba-network:
    driver: bridge

secrets:
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB.txt
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER.txt
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt
  service_id:
    file: ./secrets/SERVICE_ID.txt
  template_id:
    file: ./secrets/TEMPLATE_ID.txt
  public_key:
    file: ./secrets/PUBLIC_KEY.txt
